### PR TITLE
Added Mortality and Recovered Percentage.

### PR DESCRIPTION
**Pull request by mmixx**

### CODE REVIEW

**Comment by WarenGonzaga** [comment]
Hi, @mmixx thanks for your awesome contribution! I'm about to push the new refactored version of it. Can you send your new PR on the new version? Thanks!

**Comment by mmixx** [comment]
Sure...

**Comment by WarenGonzaga** [comment]
It's your turn @mmixx !

**Comment by mmixx** [comment]
Done...

**Pull request merged**
